config/routes.rb
Rails.application.routes.draw do
  resources :produtos

  get 'produtos/report/request'  => 'produtos#report_request'

end

app/models/produto.rb
# require "csv"

class Produto
  include Mongoid::Document
  include Mongoid::Timestamps

  validates :sku, format: {with: /^[A-Za-z0-9-]+$/, message: "Não pode ser vazio. Caracteres podem ser apenas [a-z 0-9 -]" , :multiline => true }
  validates_presence_of :nome
  validates :preco, numericality: { greater_than: 0 }
  validates :ean, length: {:allow_blank => true, :in => 8..13 }

  field :sku, type: String
  field :nome, type: String
  field :descricao, type: String
  field :quantidade, type: Integer
  field :preco, type: Float
  field :ean, type: String

  searchkick callbacks: :async

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/produtos_controller.rb
require 'date'

class ProdutosController < ApplicationController
  skip_before_action :verify_authenticity_token, :only => [:create, :update, :destroy]
  before_action :set_produto, only: [:show, :edit, :update, :destroy]
  after_action :update_produto_on_redis, only: [:edit, :update]
  after_action :destroy_produto_on_redis, only: [:destroy]

  # GET /produtos_url
  # GET /produtos.json
  def index
     if params[:keywords].present?
        Produto.reindex
        @produtos = Produto.search params[:keywords], fields: [:sku, :nome, :descricao]
      else
        @produtos = Produto.all
      end
      #report_notice = ' '
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)
    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto foi removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  # GET /produtos/report/request
  def report_request
    if params[:send_to_email].present?
      send_to = params[:send_to_email]

      report_content = build_report

      d = DateTime.now
      report_filename = 'RelatorioCadastroProdutos_' + d.strftime("%d-%m-%Y") + '.csv'
      send_report_mail_request(send_to, 'Relatório de Cadastro de Produtos', report_filename, report_content)

      $logger.info('Report generated and sent to send email queue through MailSender API')

      respond_to do |format|
          format.html { redirect_to produtos_url, notice: 'O relatório foi solicitado e será enviado para seu email em breve.' }
          format.json { render :show, status: :ok, location: @produto }
      end
    else
      redirect_to produtos_url
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      if defined? params[:id]
        @produto = get_produto_from_redis(params[:id])
      end
    end

    def update_produto_on_redis
      $redis.set(@produto._id, Marshal.dump(@produto))
    end

    def destroy_produto_on_redis
      $redis.del(params[:id])
    end

    def get_produto_from_redis(produto_id)
      if  $redis.exists(produto_id)
        produto = Marshal.load($redis.get(produto_id))
        $logger.info('Getting ' + produto_id + ' from Redis cache')
      else
        produto = Produto.find(produto_id)
        $redis.set(produto_id, Marshal.dump(produto))
        $logger.info('Adding ' + produto_id + ' to Redis cache')
      end

      return produto
    end

    def build_report
      produtos = Produto.all
      report_content = "sku,nome,descricao,quantidade,preco,ean\r\n"

      produtos.each do |produto|
        report_content += produto.sku + ',' \
                                      + produto.nome + ',' \
                                      + produto.descricao + ',' \
                                      + produto.quantidade.to_s + ',' \
                                      + produto.preco.to_s + ',' \
                                      + (produto.ean.nil? ? ' ' : produto.ean) + "\r\n"
      end

      return report_content
    end

    def send_report_mail_request(to, subject, report_filename, report_content)
      require 'net/http'
      require 'json'
      begin
        send_report_mail_endpoint = Rails.configuration.send_report_mail_request_endpoint
        uri = URI(send_report_mail_endpoint)
        http = Net::HTTP.new(uri.host, uri.port)
        req = Net::HTTP::Post.new(uri.path, {'Content-Type' =>'application/json'})
        req.body = {"to" => to, "subject" => subject, "report_filename" => report_filename, "report_content" => report_content}.to_json
        res = http.request(req)
        puts "response #{res.body}"
        puts JSON.parse(res.body)
      rescue => e
        $logger.error("failed #{e}")
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:sku, :nome, :descricao, :quantidade, :preco, :ean)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CadastroProdutos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/produtos/_form.html.erb
<%= form_for(@produto) do |f| %>
  <% if @produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produto.errors.count, "erros") %> impediram esse produto de ser salvo:</h2>

      <ul>
      <% @produto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sku %><br>
    <%= f.text_field :sku %>
  </div>
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :quantidade %><br>
    <%= f.text_field :quantidade %>
  </div>
  <div class="field">
    <%= f.label :preco %><br>
    <%= f.text_field :preco %>
  </div>
  <div class="field">
    <%= f.label :ean %><br>
    <%= f.text_field :ean %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<h1>Editing Produto</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @produto %> |
<%= link_to 'Voltar', produtos_path %>

app/views/produtos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listagem de Produtos</h1>

<br>

<div>
  <%= form_tag produtos_path, :method => :get do %>
     <%= text_field_tag :keywords, params[:keywords] %>
     <%= submit_tag "Pesquisar" %>
     <%if params[:keywords].present?%>
       <%= link_to "limpar", produtos_path %>
     <% end %>
  <% end %>
</div>
<br>

<table>
  <thead>
    <tr>
      <th>Sku</th>
      <th>Nome</th>
      <th>Descricao</th>
      <th>Quantidade</th>
      <th>Preco</th>
      <th>Ean</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= produto.sku %></td>
        <td><%= produto.nome %></td>
        <td><%= produto.descricao %></td>
        <td><%= produto.quantidade %></td>
        <td><%= produto.preco %></td>
        <td><%= produto.ean %></td>
        <td><%= link_to 'Exibir', produto %></td>
        <td><%= link_to 'Editar', edit_produto_path(produto) %></td>
        <td><%= link_to 'Remover', produto, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Produto novo', new_produto_path %>

<br><br>

<div>
  <%= form_tag produtos_path + '/report/request', :method => :get do %>
     <h3><%= label_tag 'Relatório do Cadastro de Produtos' %></h3>
     <%= text_field_tag :send_to_email, params[:send_to_email], :placeholder => 'exemplo@email.com' %>
     <%= submit_tag "Enviar" %>
  <% end %>
</div>

app/views/produtos/new.html.erb
<h1>Produto Novo</h1>

<%= render 'form' %>

<%= link_to 'Voltar', produtos_path %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sku:</strong>
  <%= @produto.sku %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @produto.nome %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @produto.descricao %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @produto.quantidade %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @produto.preco %>
</p>

<p>
  <strong>Ean:</strong>
  <%= @produto.ean %>
</p>

<%= link_to 'Editar', edit_produto_path(@produto) %> |
<%= link_to 'Voltar', produtos_path %>